// flow-typed signature: ede467b518cb986f54d9b782050c4ef7
// flow-typed version: <<STUB>>/pdfreader_v^0.2.5/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdfreader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdfreader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdfreader/lib/ColumnsParser' {
  declare module.exports: any;
}

declare module 'pdfreader/lib/LOG' {
  declare module.exports: any;
}

declare module 'pdfreader/lib/parseColumns' {
  declare module.exports: any;
}

declare module 'pdfreader/lib/parseTable' {
  declare module.exports: any;
}

declare module 'pdfreader/lib/SequentialParser' {
  declare module.exports: any;
}

declare module 'pdfreader/lib/TableParser' {
  declare module.exports: any;
}

declare module 'pdfreader/parse' {
  declare module.exports: any;
}

declare module 'pdfreader/parseAsBuffer' {
  declare module.exports: any;
}

declare module 'pdfreader/PdfReader' {
  declare module.exports: any;
}

declare module 'pdfreader/Rule' {
  declare module.exports: any;
}

declare module 'pdfreader/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdfreader/index' {
  declare module.exports: $Exports<'pdfreader'>;
}
declare module 'pdfreader/index.js' {
  declare module.exports: $Exports<'pdfreader'>;
}
declare module 'pdfreader/lib/ColumnsParser.js' {
  declare module.exports: $Exports<'pdfreader/lib/ColumnsParser'>;
}
declare module 'pdfreader/lib/LOG.js' {
  declare module.exports: $Exports<'pdfreader/lib/LOG'>;
}
declare module 'pdfreader/lib/parseColumns.js' {
  declare module.exports: $Exports<'pdfreader/lib/parseColumns'>;
}
declare module 'pdfreader/lib/parseTable.js' {
  declare module.exports: $Exports<'pdfreader/lib/parseTable'>;
}
declare module 'pdfreader/lib/SequentialParser.js' {
  declare module.exports: $Exports<'pdfreader/lib/SequentialParser'>;
}
declare module 'pdfreader/lib/TableParser.js' {
  declare module.exports: $Exports<'pdfreader/lib/TableParser'>;
}
declare module 'pdfreader/parse.js' {
  declare module.exports: $Exports<'pdfreader/parse'>;
}
declare module 'pdfreader/parseAsBuffer.js' {
  declare module.exports: $Exports<'pdfreader/parseAsBuffer'>;
}
declare module 'pdfreader/PdfReader.js' {
  declare module.exports: $Exports<'pdfreader/PdfReader'>;
}
declare module 'pdfreader/Rule.js' {
  declare module.exports: $Exports<'pdfreader/Rule'>;
}
declare module 'pdfreader/test/test.js' {
  declare module.exports: $Exports<'pdfreader/test/test'>;
}
